# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      SOLUTION_PATH: BananaGit/BananaGit.sln
      PROJECT_PATH: BananaGit/BananaGit/BananaGit.csproj
      DEPLOY_PATH: builds/BananaGit/

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x


    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/changelog
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore 
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
      env: 
        GIT_TEST_TOKEN: ${{ secrets.GIT_TEST_TOKEN }}
        GIT_TEST_USERNAME: ${{ secrets.GIT_TEST_USERNAME }}
        GIT_TEST_EMAIL: ${{ secrets.GIT_TEST_EMAIL }}
        
    - name: Publish application
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        $version = "${{ steps.semantic.outputs.new_release_version }}"
        dotnet publish ${{env.SOLUTION_PATH}} -c Release -r win-x64 --self-contained true -o ${{env.DEPLOY_PATH}}

    - name: Zip release
      if: steps.semantic.outputs.new_release_published == 'true'
      run: Compress-Archive -Path ${{ env.DEPLOY_PATH }}* -DestinationPath BananaGit-v${{ steps.semantic.outputs.new_release_version }}-win-x64.zip
    
    - name: Upload Release Asset
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.semantic.outputs.new_release_upload_url }}
        asset_path: ./BananaGit-v${{ steps.semantic.outputs.new_release_version }}-win-x64.zip
        asset_name: BananaGit-v${{ steps.semantic.outputs.new_release_version }}-win-x64.zip
        asset_content_type: application/zip
    
    - name: Upload artifact
      if: steps.semantic.outputs.new_release_published != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: BananaGit
        path: ${{env.DEPLOY_PATH}}
        retention-days: 3
