# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      SOLUTION_PATH: BananaGit/BananaGit.sln
      DEPLOY_PATH: builds/BananaGit/

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore 
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
      env: 
        GIT_TEST_TOKEN: ${{ secrets.GIT_TEST_TOKEN }}
        GIT_TEST_USERNAME: ${{ secrets.GIT_TEST_USERNAME }}
        GIT_TEST_EMAIL: ${{ secrets.GIT_TEST_EMAIL }}

    - name: Publish application
      run: dotnet publish BananaGit/BananaGit/BananaGit.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o builds/BananaGit/
      env:
        DEPLOY_PATH: builds/BananaGit/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BananaGit 
        path: builds/BananaGit/
        retention-days: 7
